namespace: ernstov
blanks-error-test-2126:
  defines: runnable
  containers:
    blanks-error-test-2126:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: blanks-error-test-2126
      port: 8080
      protocol: tcp
